config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :index, :update, :show]

  get "logout", to: "sessions#destroy" 
  resource :session
  
  resources :cats do
    member do
      resources :cat_rental_requests
    end
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#
require 'bcrypt'
class User < ActiveRecord::Base
  
  has_many :cats
  has_many :cat_rental_requests, class_name: 'CatRentalRequest', foreign_key: :user_id 
  has_many :rentals, :through => :cat_rental_requests, :source => :cat
  
  def password
    @password
  end
  
  validates :username, :password_digest, :session_token, presence: true
  validates :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  
  before_validation :ensure_session_token
  
  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token  
  end
  
  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def self.find_by_credentials(user_name, password)
    user = User.find_by_username(user_name)
    return user if !user.nil? && user.is_password?(password)
    nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :not_logged_in, :only => [:create, :new]
  def new
    @user = User.new
    render :new
  end

  def create
 
    @user = User.new(user_params)

    if @user.save
      redirect_to user_url(@user)
    else
      flash[:errors] =  @user.errors.full_messages
      render :new
    end
  end
  
  def index
    @users = User.all
    render :index
  end
  
  
  private
  
  def not_logged_in
    # fail
    unless current_user.nil?       
      # (self.flash()).[]=(:errors, ["You cannot create..."])      
      flash[:errors] = ["You cannot create a new user while logged in"]
      redirect_to cats_url # halts request cycle
     end
   end
  
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<ul>
<% @users.each do |user| %>
  <li>
    <%= link_to user.username, user_url(user) %>
  </li>
<% end %>
<h1><%= link_to "Check cat list", cats_url %></h1>
  <br>

<%= link_to "Create new user", new_user_url %>

</ul>

<%= %>

app/views/users/new.html.erb
<h1>Create new user!</h1>

<form action= "/users" method="POST">
  <input type= "hidden"
   name = "authenticity_token"
   value = "<%= form_authenticity_token %>">
  <label for="user_user_name"> Username </label>
  <input 
    type="text" 
    name="user[username]" 
    placeholder="" 
    value="<%= @user[:username] %>"><br/>
  <label for="user_password"> Password </label>
  <input
    type="password"
    name="user[password]"><br/>
    
  <input type="submit" value="Log In!">
</form>

app/views/users/show.html.erb
<%= link_to "Back to user list", users_url %><br>