config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :index, :update, :show]

  get "logout", to: "sessions#destroy" 
  resource :session
  
  resources :cats do
    member do
      resources :cat_rental_requests
    end
  end

end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string(255)      default("PENDING")
#  created_at :datetime
#  updated_at :datetime
#

class CatRentalRequest < ActiveRecord::Base
  belongs_to(
    :cat,
    :class_name => 'Cat'
  )
  
  belongs_to(
  :requester,
  :class_name => 'User',
  :foreign_key => :user_id
  )
  
  
  before_validation(on: :status) do
    self.status ||= "PENDING"
  end
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, :inclusion => { in: %w(APPROVED DENIED PENDING), 
                                      message: "%{value} is not a valid status."}
  
   validate :overlapping_approved_requests
   validate :start_date_before_end_date
  def overlapping_requests    
    CatRentalRequest.all.where(<<-SQL,start_date,end_date,start_date, end_date,cat_id)
    ((? BETWEEN start_date AND end_date) OR (? BETWEEN start_date AND end_date) OR
    (start_date < ? AND end_date > ?)) AND (cat_id = ?)
    SQL
  end
  
  def overlapping_approved_requests
    approved_stati = overlapping_requests.where(status: 'APPROVED')
    
    unless approved_stati.empty?
      errors[:status] << "Two overlapping requests cannot be approved"      
    end
  end
  
  def start_date_before_end_date
    unless start_date < end_date
      error[:base] << "Start date must be before end date"
    end
  end
  
  def rental_persisted
   if self.persisted? 
     return 'Update Cat Rental Request'
   else
     return 'Create Cat Rental Request'
   end    
  end  
  
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  
  def index
    @cat_rental_requests = CatRentalRequest.all.order(:start_date)
    render :index  
  end
  
  def show
    @cat_rental_request = CatRentalRequest.find(params[:id])
    render :show
  end
  
  def new
    @cat_rental_request = CatRentalRequest.new

    render :new
  end
  
  def create
    @cat_rental_request = CatRentalRequest.new(rental_request_params)
    @cat_rental_request.user_id = current_user.id
    if @cat_rental_request.save
      redirect_to cat_url(@cat_rental_request.cat_id)
    else
      flash[:errors] = @cat_rental_request.errors.full_messages
      render :new
    end
  end
  
  def edit
    @cat_rental_request = CatRentalRequest.find(params[:id])
    render :edit
  end
  
  def update
    @cat_rental_request = CatRentalRequest.find(params[:id])
    @cat_rental_request.update(rental_request_params)
    redirect_to cat_url(@cat_rental_request)
  end
  

  
  private
    
  def rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
  end
end

app/helpers/cat_rental_request_helper.rb
module CatRentalRequestHelper
end

app/views/cat_rental_requests/_form.html.erb
<% if @cat_rental_request.persisted? %>
  <form action = "<%= cat_rental_request_url(@cat_rental_request) %>" method="post">
    <input type="hidden" name="_method" value="patch">
<% else %>
  <form action = "<%= cat_rental_requests_url %>" method="post">
<% end %>

  <input type = 'hidden' name = "authenticity_token"
                  value = '<%= form_authenticity_token %>'>

  <label>
  <select name = "cat_rental_request[cat_id]" >
        <% Cat.all.each do |cat| %>
        <option value = "<%= cat.id %>"
            selected = "<%= cat.name %>">
            <%= cat.name %>
          </option>
          <% end %></label><br>
 <label>
   <label>
   Start Date: <input 
           type="date" 
           name = "cat_rental_request[start_date]"
           value = "<%= @cat_rental_request.start_date%>">
         </label><br>
  
   <label>
     <label>
     End date: <input 
             type="date" 
             name = "cat_rental_request[end_date]"
             value = "<%= @cat_rental_request.end_date %>">
           </label><br>
  
     <label>


  <% button_name = @cat_rental_request.rental_persisted %>

  <input type="submit" value="<%= button_name %>">
</form>

app/views/cat_rental_requests/edit.html.erb
<%= render partial: 'form' %>

app/views/cat_rental_requests/index.html.erb
<ul>
<% @cat_rental_requests.each do |cat| %>
  <li>
    <%= link_to cat.name, cat_url(cat) %>
  </li>
<% end %>
<%= link_to "Create new cat", new_cat_url %>
</ul>

app/views/cat_rental_requests/new.html.erb
<%= render partial: 'form' %>

app/views/cat_rental_requests/show.html.erb
<table style="width:300px">
  <th>
     <td> 
       Name
     </td>
     <td> 
       start_date
     </td>
      <td> 
       end_date 
     </td>
     <td>
       Status
     </td>
  </th>
   <tr>
     <td> 
      <%= Cat.find(@cat_rental_request.cat_id) %>
     </td>
     <td> 
      <%= @cat_rental_request.start_date %>
     </td>
      <td> 
        <%= @cat_rental_request.end_date %>
     </td>
     <td> 
       <%= @cat_rental_request.status %>
     </td>
   </tr>
</table>
<%= link_to "Update Cat Rental Request", edit_cat_cat_rental_request_url(@cat_rental_request) %><br>

<%= link_to "Back to Cat Rental List", cat_cat_rental_request_url(@cat_rental_request.cat_id) %>