config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :index, :update, :show]

  get "logout", to: "sessions#destroy" 
  resource :session
  
  resources :cats do
    member do
      resources :cat_rental_requests
    end
  end

end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id         :integer          not null, primary key
#  age        :integer          not null
#  birth_date :string(255)      not null
#  color      :string(255)      not null
#  name       :string(255)      not null
#  sex        :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Cat < ActiveRecord::Base
  COLORS = %w(black brown white orange calico)
  belongs_to :owner, class_name: "User", foreign_key: :user_id 
  
  has_many(
    :cat_rental_requests,
    :class_name => 'CatRentalRequest',
    dependent: :destroy
  )
  
  has_many :requests, :through => :cat_rental_requests, :source => :requester
  
  # def destroy
  #   cat_rental_requests.destroy
  #   self.destroy
  # end
  
  validates :age, :numericality  => true, :presence  => true
  validates :birth_date, :color, :name, :sex, :presence  => true
  validates :color, :inclusion  => { in: COLORS,
                                      message: "%{value} is not a valid color."}
  validates :sex, :inclusion  => { in: %w(M F), message: "%{value} is not a valid sex."}
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :editor_owns_cat, only: [:edit, :update]
  
  def index
    @cats = Cat.all
    render :index  
  end
  
  def show
    @cat = Cat.find(params[:id])
    render :show
  end
  
  def new
    @cat = Cat.new
    render :new
  end
  
  def create
    @cat = Cat.new(cats_params)
    @cat.user_id = current_user.id
    
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash[:errors] = @cat.errors.full_messages
      render :new
    end
  end
  
  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end
  
  def update
    @cat = Cat.find(params[:id])
    @cat.update(cats_params)
    redirect_to cat_url(@cat)
  end
  
  private
    
  def cats_params
    params.require(:cat).permit(:age, :birth_date, :color, :name, :sex, :user_id)
  end
  
  def editor_owns_cat
    @cat = Cat.find(params[:id]) 
    unless @cat.user_id == current_user.id
      flash[:errors] = ["Only owners can edit/update cat info."]
      redirect_to cats_url
    end
  end
  
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<% if @cat.persisted? %>
  <form action = "<%= cat_url(@cat) %>" method="post">
    <input type="hidden" name="_method" value="patch">
<% else %>
  <form action = "<%= cats_url %>" method="post">
<% end %>

  <input type = 'hidden' name = "authenticity_token"
                  value = '<%= form_authenticity_token %>'>
  <label>
  Name: <input 
          type="text" 
          name = "cat[name]" 
          placeholder = "Enter cat name"
          value = "<%= @cat.name %>">
        </label><br>
  <label>
  Age: <input 
          type="number" 
          name = "cat[age]"
          placholder = "enter cat age"
          value = "<%= @cat.age %>"><br>
        </label>
  <label>
  Birth Date: <input 
          type="date" 
          name = "cat[birth_date]"
          value = "<%= @cat.birth_date %>">
        </label><br>
  
  <label>
  Color: <select name = "cat[color]">
           <% Cat::COLORS.each do |color| %>
           <option value = "<%= color %>"
             selected = "<%= @cat.color %>">
             <%= color %>
           </option>
           <% end %>
         </select></label><br>
 <label>
  Sex: <input type="radio" name = "cat[sex]" value = "M">Male<br>
       <input type="radio" name = "cat[sex]" value = "F">Female<br>
 </label>

  <% button_name = @cat.persisted? ? 'Update Cat' : 'Create Cat' %>

  <input type="submit" value="<%= button_name %>">
</form>

app/views/cats/edit.html.erb
<%= render partial: 'form' %>

app/views/cats/index.html.erb
<ul>
<% @cats.each do |cat| %>
  <li>
    <%= link_to cat.name, cat_url(cat) %>
  </li>
<% end %>
<%= link_to "Create new cat", new_cat_url %>
</ul>

app/views/cats/new.html.erb
<%= render partial: 'form' %>

app/views/cats/show.html.erb
<table style="width:300px">
  <th>
     <td> 
       Name
     </td>
     <td> 
      Birth_date
     </td>
      <td> 
        Color
     </td>
     <td> 
       Age
     </td>
     <td> 
       Sex
     </td>
   </th>
   <tr>
     <td> 
      <%= @cat.name %>
     </td>
     <td> 
      <%= @cat.birth_date %>
     </td>
      <td> 
        <%= @cat.color %>
     </td>
     <td> 
       <%= @cat.age %>
     </td>
     <td> 
       <%= @cat.sex %>
     </td>
   </tr>
</table>

<table>
  <th>
    <td>
      Renter
    </td>
    <td>
      Start Date
    </td>
    <td>
      End Date
    </td>
  </th>
    <% @cat.cat_rental_requests.each do |cat_rental|  %>
    <tr>
      <td>
        <%= cat_rental.requester.username %>
      </td>
      <td>
      <%= cat_rental.start_date %>
    </td>
    <td>
      <%= cat_rental.end_date %>
    </td>
  </tr>
  <% end %>  
</table>

<%= link_to "Update cat info", edit_cat_url(@cat) %><br>
<%= link_to "Back to cat list", cats_url %><br>
<%= link_to "Create Rental Request", new_cat_rental_request_url %>